### ISSUE TITLE
The Hive- problem with elasticsearch/ cluster unreachable

### ISSUE THREAD

**Issue by k3rnon** [TheHive-Project/TheHiveDocs#101]
Hello! I am trying to install thehive but I have some problem with elasticsearch. Cortex/ Thehive works but cant creat first database and elasticsearch cluster is unreachable. Dunno what to do... I read a lot of things about it and still doesnt work. This is my log:
 at org.elasticsearch.gateway.MetaStateService.loadGlobalState(MetaStateService.java:113)
        at org.elasticsearch.gateway.MetaStateService.loadFullState(MetaStateService.java:57)
        at org.elasticsearch.gateway.GatewayMetaState.<init>(GatewayMetaState.java:92)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.elasticsearch.common.inject.DefaultConstructionProxyFactory$1.newInstance(DefaultConstructionProxyFactory.java:49)
        at org.elasticsearch.common.inject.ConstructorInjector.construct(ConstructorInjector.java:86)
        at org.elasticsearch.common.inject.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:116)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:47)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:825)
        at org.elasticsearch.common.inject.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:43)
        at org.elasticsearch.common.inject.Scopes$1$1.get(Scopes.java:59)
        at org.elasticsearch.common.inject.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:50)
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:191)
        at org.elasticsearch.common.inject.InjectorBuilder$1.call(InjectorBuilder.java:183)
        at org.elasticsearch.common.inject.InjectorImpl.callInContext(InjectorImpl.java:818)
        at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:183)
        at org.elasticsearch.common.inject.InjectorBuilder.loadEagerSingletons(InjectorBuilder.java:176)
        at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:161)
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:96)
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:96)
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70)
        at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:42)
        at org.elasticsearch.node.Node.<init>(Node.java:499)
        at org.elasticsearch.node.Node.<init>(Node.java:245)
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:123)
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:70)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:134)
        at org.elasticsearch.cli.Command.main(Command.java:90)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84)
Caused by: java.io.IOException: failed to read [id:19, legacy:false, file:/var/lib/elasticsearch/nodes/0/_state/global-19.st]
        at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:328)
        ... 37 more
Caused by: java.lang.IllegalArgumentException: Unexpected field [cluster_uuid_committed]
        at org.elasticsearch.cluster.metadata.MetaData$Builder.fromXContent(MetaData.java:1181)
        at org.elasticsearch.cluster.metadata.MetaData$2.fromXContent(MetaData.java:1211)
        at org.elasticsearch.cluster.metadata.MetaData$2.fromXContent(MetaData.java:1202)
        at org.elasticsearch.gateway.MetaDataStateFormat.read(MetaDataStateFormat.java:203)
        at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:323)
        ... 37 more

4 errors
        at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:361) ~[elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:164) ~[elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:96) ~[elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:96) ~[elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70) ~[elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:42) ~[elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.node.Node.<init>(Node.java:499) ~[elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.16.jar:5.6.16]
        ... 6 more

elasticsearch.yml

<# ----------------------------------- Memory -----------------------------------/>
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
#
<# Make sure that the heap size is set to about half the memory available
<# on the system and that the owner of the process is allowed to use this
<# limit.
#
<# Elasticsearch performs poorly when the system is swapping the memory.
#
<# ---------------------------------- Network -----------------------------------
#
<# Set the bind address to a specific IP (IPv4 or IPv6):
#
#network.host: 127.0.0.1
#script.inline: true
#cluster.name: hive
#thread_pool.index.queue_size: 100000
#thread_pool.search.queue_size: 100000
#thread_pool.bulk.queue_size: 100000
#
<# Set a custom port for HTTP:
#
#http.port: 9200
#
<# For more information, consult the network module documentation.

**Comment by k3rnon** [comment]
#path.logs: /path/to/logs
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
#network.host: 127.0.0.1
#
#
#
#
#
# Set a custom port for HTTP:
#
#http.port: 9200
#
# For more information, consult the network module documentation.
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
#discovery.zen.ping.unicast.hosts: ["host1", "host2"]
#
# Prevent the "split brain" by configuring the majority of nodes (total number of master-eligible nodes / 2 + 1):
#
#discovery.zen.minimum_master_nodes: 3
#
# For more information, consult the zen discovery module documentation.
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
#gateway.recover_after_nodes: 3
#
# For more information, consult the gateway module documentation.
#
# ---------------------------------- Various -----------------------------------
#
# Require explicit names when deleting indices:
#
#action.destructive_requires_name: true
network.host: 127.0.0.1
script.inline: true
cluster.name: hive
thread_pool.index.queue_size: 100000
thread_pool.search.queue_size: 100000
thread_pool.bulk.queue_size: 1000

**Comment by k3rnon** [comment]
#path.logs: /path/to/logs
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
#network.host: 127.0.0.1
#
#
#
#
#
# Set a custom port for HTTP:
#
#http.port: 9200
#
# For more information, consult the network module documentation.
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
#discovery.zen.ping.unicast.hosts: ["host1", "host2"]
#
# Prevent the "split brain" by configuring the majority of nodes (total number of master-eligible nodes / 2 + 1):
#
#discovery.zen.minimum_master_nodes: 3
#
# For more information, consult the zen discovery module documentation.
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
#gateway.recover_after_nodes: 3
#
# For more information, consult the gateway module documentation.
#
# ---------------------------------- Various -----------------------------------
#
# Require explicit names when deleting indices:
#
#action.destructive_requires_name: true
network.host: 127.0.0.1
script.inline: true
cluster.name: hive
thread_pool.index.queue_size: 100000
thread_pool.search.queue_size: 100000
thread_pool.bulk.queue_size: 1000

**Comment by k3rnon** [comment]
- #path.logs: /path/to/logs
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
#network.host: 127.0.0.1
#
#
#
#
#
# Set a custom port for HTTP:
#
#http.port: 9200
#
# For more information, consult the network module documentation.
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
#discovery.zen.ping.unicast.hosts: ["host1", "host2"]
#
# Prevent the "split brain" by configuring the majority of nodes (total number of master-eligible nodes / 2 + 1):
#
#discovery.zen.minimum_master_nodes: 3
#
# For more information, consult the zen discovery module documentation.
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
#gateway.recover_after_nodes: 3
#
# For more information, consult the gateway module documentation.
#
# ---------------------------------- Various -----------------------------------
#
# Require explicit names when deleting indices:
#
#action.destructive_requires_name: true
network.host: 127.0.0.1
script.inline: true
cluster.name: hive
thread_pool.index.queue_size: 100000
thread_pool.search.queue_size: 100000
thread_pool.bulk.queue_size: 1000

**Comment by k3rnon** [comment]
sudo tail -n24 /var/log/elasticsearch/elasticsearch.log
        at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:328)
        ... 37 more
Caused by: java.lang.IllegalArgumentException: Unexpected field [cluster_uuid_committed]
        at org.elasticsearch.cluster.metadata.MetaData$Builder.fromXContent(MetaData.java:1181)
        at org.elasticsearch.cluster.metadata.MetaData$2.fromXContent(MetaData.java:1211)
        at org.elasticsearch.cluster.metadata.MetaData$2.fromXContent(MetaData.java:1202)
        at org.elasticsearch.gateway.MetaDataStateFormat.read(MetaDataStateFormat.java:203)
        at org.elasticsearch.gateway.MetaDataStateFormat.loadLatestState(MetaDataStateFormat.java:323)
        ... 37 more

4 errors
        at org.elasticsearch.common.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:361) ~[elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.common.inject.InjectorBuilder.injectDynamically(InjectorBuilder.java:164) ~[elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.common.inject.InjectorBuilder.build(InjectorBuilder.java:96) ~[elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:96) ~[elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70) ~[elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.common.inject.ModulesBuilder.createInjector(ModulesBuilder.java:42) ~[elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.node.Node.<init>(Node.java:499) ~[elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132) ~[elasticsearch-5.6.16.jar:5.6.16]
        ... 6 more

**Comment by k3rnon** [comment]
sudo tail -f /var/log/elas                                                                                                                                                             ticsearch/hive.log
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:96) ~                                                                                                                                                             [elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.common.inject.Guice.createInjector(Guice.java:70) ~                                                                                                                                                             [elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.common.inject.ModulesBuilder.createInjector(Modules                                                                                                                                                             Builder.java:42) ~[elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.node.Node.<init>(Node.java:499) ~[elasticsearch-5.6                                                                                                                                                             .16.jar:5.6.16]
        at org.elasticsearch.node.Node.<init>(Node.java:245) ~[elasticsearch-5.6                                                                                                                                                             .16.jar:5.6.16]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:233) ~[                                                                                                                                                             elasticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:233) ~[ela                                                                                                                                                             sticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:342) ~[elas                                                                                                                                                             ticsearch-5.6.16.jar:5.6.16]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:132                                                                                                                                                             ) ~[elasticsearch-5.6.16.jar:5.6.16]

**Comment by k3rnon** [comment]
Here is elasticsearch configuration and log:
 ls -l /var/lib/elasticsearch/nodes/0/_state/
total 32
-rw-r--r--. 1 elasticsearch elasticsearch 21838 Jun  3 11:09 global-19.st
-rw-r--r--. 1 elasticsearch elasticsearch   111 Jun  3 11:09 manifest-39.st
-rw-r--r--. 1 elasticsearch elasticsearch    71 Jun  5 14:31 node-56.st

4) Error injecting constructor, ElasticsearchException[java.io.IOException: failed to read [id:19, legacy:false, file:/var/lib/elasticsearch/nodes/0/_state/global-19.st]]; nested: IOException[failed to read [id:19, legacy:false, file:/var/lib/elasticsearch/nodes/0/_state/global-19.st]]; nested: IllegalArgumentException[Unexpected field [cluster_uuid_committed]];
  at org.elasticsearch.gateway.GatewayMetaState.<init>(Unknown Source)
  while locating org.elasticsearch.gateway.GatewayMetaState
    for parameter 4 at org.elasticsearch.gateway.GatewayService.<init>(Unknown Source)
  while locating org.elasticsearch.gateway.GatewayService
Caused by: ElasticsearchException[java.io.IOException: failed to read [id:19, legacy:false, file:/var/lib/elasticsearch/nodes/0/_state/global-19.st]]; nested: IOException[failed to read [id:19, legacy:false, file:/var/lib/elasticsearch/nodes/0/_state/global-19.st]]; nested: IllegalArgumentException[Unexpected field [cluster_uuid_committed]];
 **YML file**

========================` Elasticsearch Configuration =========================

#
`#` NOTE: Elasticsearch comes with reasonable defaults for most settings.
`#`       Before you set out to tweak and tune the configuration, make sure you
`#`       understand what are you trying to accomplish and the consequences.
#
`#` The primary way of configuring a node is via this file. This template lists
`#` the most important settings you may want to configure for a production cluster.
#
`#` Please consult the documentation for further information on configuration options:
`#` https://www.elastic.co/guide/en/elasticsearch/reference/index.html
#
`#` ---------------------------------- Cluster -----------------------------------
#
`#` Use a descriptive name for your cluster:
#
`#cluster.name:` my-application
#
`#` ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
#node.name: node-1
#
# Add custom attributes to the node:
#
#node.attr.rack: r1
#
`#` ----------------------------------- Paths ------------------------------------
#
`#` Path to directory where to store the data (separate multiple locations by comma):
#
`#path.data:` /path/to/data
#
`#` Path to log files:
#
`#path.logs:` /path/to/logs
#
`#` ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
#
`#` Make sure that the heap size is set to about half the memory available
`#` on the system and that the owner of the process is allowed to use this
`#` limit.
#
`#` Elasticsearch performs poorly when the system is swapping the memory.
#
`#` ---------------------------------- Network -----------------------------------
#
`#` Set the bind address to a specific IP (IPv4 or IPv6):
#
#network.host: 127.0.0.1
#
#
#
#
#
`#` Set a custom port for HTTP:
#
http.port: 9200
#
`#` For more information, consult the network module documentation.
#
`#` --------------------------------- Discovery ----------------------------------
#
`#` Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
#discovery.zen.ping.unicast.hosts: ["host1", "host2"]
#
`#` Prevent the "split brain" by configuring the majority of nodes (total number of master-eligible nodes / 2 + 1):
#
#discovery.zen.minimum_master_nodes: 3
#
`#` For more information, consult the zen discovery module documentation.
#
`#` ---------------------------------- Gateway -----------------------------------
#
`#` Block initial recovery after a full cluster restart until N nodes are started:
#
#gateway.recover_after_nodes: 3
#
`#` For more information, consult the gateway module documentation.
#
`#` ---------------------------------- Various -----------------------------------
#
`#` Require explicit names when deleting indices:
#
action.destructive_requires_name: true
network.host: 0.0.0.0
script.inline: true
cluster.name: hive
thread_pool.index.queue_size: 100000
thread_pool.search.queue_size: 100000
thread_pool.bulk.queue_size: 1000
cluster.name: hive
bootstrap.memory_lock: true
discovery.type: single-node
``

**Comment by k3rnon** [comment]
Still dunno what to do with elasticsearch;/

elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2019-06-07 13:05:41 CEST; 1min 46s ago
     Docs: http://www.elastic.co
  Process: 7346 ExecStart=/usr/share/elasticsearch/bin/elasticsearch -p ${PID_DIR}/elasticsearch.pid --quiet -Edefault.path.logs=${LOG_DIR} -Edefault.path.data=${DATA_DIR} -Edefault.path.conf=${CONF_DIR} (code=exited, status=1/FAILURE)
  Process: 7344 ExecStartPre=/usr/share/elasticsearch/bin/elasticsearch-systemd-pre-exec (code=exited, status=0/SUCCESS)
 Main PID: 7346 (code=exited, status=1/FAILURE)

Jun 07 13:05:38 s-thehive-ta01 systemd[1]: Starting Elasticsearch...
Jun 07 13:05:38 s-thehive-ta01 systemd[1]: Started Elasticsearch.
Jun 07 13:05:41 s-thehive-ta01 systemd[1]: elasticsearch.service: main process exited, code=exited, status=1/FAILURE
Jun 07 13:05:41 s-thehive-ta01 systemd[1]: Unit elasticsearch.service entered failed state.
Jun 07 13:05:41 s-thehive-ta01 systemd[1]: elasticsearch.service failed.

**Comment by k3rnon** [comment]
# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please consult the documentation for further information on configuration options:
# https://www.elastic.co/guide/en/elasticsearch/reference/index.html
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
#cluster.name: hive
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
#node.name: node-1
#
# Add custom attributes to the node:
#
#node.attr.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
#
#path.data: /path/to/data
#
# Path to log files:
#
#path.logs: /path/to/logs
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
#bootstrap.memory_lock: true
#
# Make sure that the heap size is set to about half the memory available
# on the system and that the owner of the process is allowed to use this
# limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
#network.host: 192.168.0.1
#
# Set a custom port for HTTP:
#
http.port: 9200
#
# For more information, consult the network module documentation.
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
#discovery.zen.ping.unicast.hosts: ["host1", "host2"]
#
# Prevent the "split brain" by configuring the majority of nodes (total number of master-eligible nodes / 2 + 1):
#
#discovery.zen.minimum_master_nodes: 3
#
# For more information, consult the zen discovery module documentation.
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
#gateway.recover_after_nodes: 3
#
# For more information, consult the gateway module documentation.
#
# ---------------------------------- Various -----------------------------------
#
# Require explicit names when deleting indices:
#
#action.destructive_requires_name: true
http.host: 127.0.0.1
transport.host: 127.0.0.1
script.inline: on
cluster.name: hive
thread_pool.index.queue_size: 100000
thread_pool.search.queue_size: 100000
thread_pool.bulk.queue_size: 100000
patch.repo: ["/opt/backup"]
