### ISSUE TITLE
HTTP chunk size exceeds the configured limit of 1048576 bytes

### ISSUE THREAD

**Issue by Jav3k** [TheHive-Project/TheHiveDocs#175]
TheHive 3.4 Training VM

Hello. I'm using TheHive API to create alert -> case -> task -> log.
My log is .pdf file attachment. But the file size is always different. And most often it is more than 1 MB.

How to increase http chunk size?

From logs:
```
2020-06-01 07:52:02,329 [INFO] from org.elastic4play.ErrorHandler in application-akka.actor.default-dispatcher-16 - POST /api/case/task/1lPdbnIBSO-PpzIoIpqN/log returned 500
akka.http.scaladsl.model.EntityStreamException: HTTP chunk size exceeds the configured limit of 1048576 bytes
	at akka.http.impl.engine.parsing.HttpMessageParser$$anonfun$2.applyOrElse(HttpMessageParser.scala:330)
	at akka.http.impl.engine.parsing.HttpMessageParser$$anonfun$2.applyOrElse(HttpMessageParser.scala:328)
	at akka.stream.impl.fusing.Collect$$anon$6.$anonfun$wrappedPf$1(Ops.scala:217)
	at akka.stream.impl.fusing.SupervisedGraphStageLogic.withSupervision(Ops.scala:178)
	at akka.stream.impl.fusing.Collect$$anon$6.onPush(Ops.scala:219)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:515)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:478)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:374)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:588)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:474)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:563)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:730)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:745)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:655)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
	at akka.actor.ActorCell.invoke(ActorCell.scala:561)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

```

**Comment by LouisianaNutSack49** [comment]
Hmm.

**Comment by Jav3k** [comment]
Moved to https://github.com/TheHive-Project/TheHive/issues/1484
