### ISSUE TITLE
Missing LDAP configuration for TheHive 4.0

### ISSUE THREAD

**Issue by b00lpy** [TheHive-Project/TheHiveDocs#222]
I'm trying to install TheHive 4.0 with LDAP auth enabled. My standard account profile is made witouth domain name like `b00lpy` and not `b00lpy@domain.com`. 
It would be cool to configure user creation without forcing inserting the domain if it does not exists.

By the way, changing configuration from old version like this: 

```

auth{
provider = [ldap,local]
method.basic = true
ldap {
    serverName = "ldap.sever:389"
    bindDN = "CN=xxx,OU=xxxOU=CV xxx,DC=domain,DC=com"
    bindPW = "xxx"
    baseDN = "OU=CV xxx,DC=domain,DC=com"
                 filter = "(filter_name={0})"
  }
  }

```

To this:

```
auth.defaultUserDomain: "domain.com"
auth {
	providers: [
		{name: session} # required !
		{name:ldap 
		 serverName = "ldap.sever:389"
		 bindDN = "CN=xxx,OU=xxxOU=CV xxx,DC=domain,DC=com"
		 bindPW = "xxx"
		 baseDN = "OU=CV xxx,DC=domain,DC=com"
                 filter = "(filter_name={0})"
		 }
		{name: local}
		{name: key}
	]
}

```

The login seems not working and raises an error :  

```


thehive4         | [warn] o.t.s.ErrorHandler [|] GET /api/status returned 400
thehive4         | org.thp.scalligraph.BadConfigurationError: Configuration hosts is missing
thehive4         |      at org.thp.scalligraph.auth.AuthSrvProvider$RichConfig.$anonfun$getOrFail$1(AuthSrv.scala:41)
thehive4         |      at scala.Option.fold(Option.scala:251)
thehive4         |      at org.thp.scalligraph.auth.AuthSrvProvider$RichConfig.getOrFail(AuthSrv.scala:41)
thehive4         |      at org.thp.scalligraph.auth.LdapAuthProvider.$anonfun$apply$4(LdapAuthSrv.scala:94)
thehive4         |      at scala.util.Success.flatMap(Try.scala:251)
thehive4         |      at org.thp.scalligraph.auth.LdapAuthProvider.$anonfun$apply$3(LdapAuthSrv.scala:93)
thehive4         |      at scala.util.Success.flatMap(Try.scala:251)
thehive4         |      at org.thp.scalligraph.auth.LdapAuthProvider.$anonfun$apply$2(LdapAuthSrv.scala:92)
thehive4         |      at scala.util.Success.flatMap(Try.scala:251)
thehive4         |      at org.thp.scalligraph.auth.LdapAuthProvider.$anonfun$apply$1(LdapAuthSrv.scala:91)


```

Note, it would be useful if a mapping between old and new settings parameters is provided in order to perform a proper migration.

**Comment by b00lpy** [comment]
For those facing the same problem, I did it.

Create user with login value: `username@domain.com`. The login form will be submitted only with `username`.  

Inside `application.conf` file set auth section like this:

```

auth.defaultUserDomain: "domain.com"
auth {
	providers: [
		{name: session} # required !
		{
                 name:ldap 
		 hosts = ["ldap.sever:389"] # That's the difference between TH 3.4 and TH 4
		 bindDN = "CN=xxx,OU=xxxOU=CV xxx,DC=domain,DC=com"
		 bindPW = "xxx"
		 baseDN = "OU=CV xxx,DC=domain,DC=com"
                 filter = "(filter_name={0})"
		 }
		{name: local}
		{name: key}
	]
}


```
