### ISSUE TITLE
ElasticSearch not staying running

### ISSUE THREAD

**Issue by GregorioSecurity** [TheHive-Project/TheHiveDocs#90]
Hello,
I'm trying to get my Hive running, but after the 'docker-compose up' finishes and look at the running dockers, all three docker containers start but after about a minute the elasticsearch docker exits. Does anyone have a solution for this? I'm running docker-ce on Oracle Linux 7.6 

```
# docker ps
CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS              PORTS                              NAMES
07299e22c383        thehiveproject/thehive:latest   "/opt/thehive/entryp…"   4 days ago          Up 4 days           0.0.0.0:9000->9000/tcp             thehive_thehive_1
0b99ecf4ecfd        thehiveproject/cortex:latest    "/opt/cortex/entrypo…"   4 days ago          Up 4 days           9000/tcp, 0.0.0.0:9001->9001/tcp   thehive_cortex_1
# docker container ls -a
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS                      PORTS                              NAMES
07299e22c383        thehiveproject/thehive:latest                         "/opt/thehive/entryp…"   4 days ago          Up 4 days                   0.0.0.0:9000->9000/tcp             thehive_thehive_1
0b99ecf4ecfd        thehiveproject/cortex:latest                          "/opt/cortex/entrypo…"   4 days ago          Up 4 days                   9000/tcp, 0.0.0.0:9001->9001/tcp   thehive_cortex_1
be6e47759595        docker.elastic.co/elasticsearch/elasticsearch:5.6.0   "/bin/bash bin/es-do…"   4 days ago          Exited (78) 6 minutes ago                                      thehive_elasticsearch_1

```
When I try to log in a popup says that ElasticSearch Cluster cannot be reached.
This is what I get from the docker-compose up feed when I try to log in. 
```

thehive_1        | [info] o.e.ErrorHandler - POST /api/login returned 500
thehive_1        | org.elasticsearch.client.transport.NoNodeAvailableException: None of the configured nodes are available: [{#transport#-1}{zm-xqKFST3uZPeKxjGWW_A}{172.18.0.2}{172.18.0.2:9300}]
thehive_1        |      at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:347)
thehive_1        |      at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:245)
thehive_1        |      at org.elasticsearch.client.transport.TransportProxyClient.execute(TransportProxyClient.java:59)
thehive_1        |      at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:366)
thehive_1        |      at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:408)
thehive_1        |      at org.elasticsearch.client.support.AbstractClient$IndicesAdmin.execute(AbstractClient.java:1256)
thehive_1        |      at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:80)
thehive_1        |      at org.elasticsearch.action.ActionRequestBuilder.execute(ActionRequestBuilder.java:54)
thehive_1        |      at com.sksamuel.elastic4s.admin.IndexAdminExecutables$IndexExistsDefinitionExecutable$.apply(IndexAdminExecutables.scala:53)
thehive_1        |      at com.sksamuel.elastic4s.admin.IndexAdminExecutables$IndexExistsDefinitionExecutable$.apply(IndexAdminExecutables.scala:50)

```

**Comment by GregorioSecurity** [comment]
I actually figured it out, I just ran ' docker run -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" docker.elastic.co/elasticsearch/elasticsearch:5.6.0' and it worked fine.

**Comment by nadouani** [comment]
This is not really a TheHive issue, but it's related to the ES docker image, Sorry I don't know how we can help.
